import { Palette as SlintPalette } from "std-widgets.slint";

export global Palette {
    out property <color> primary: SlintPalette.accent-background;
    out property <color> success: #22c55e;
    out property <color> warning: #f97316;
    out property <color> background: SlintPalette.background;
    out property <color> card-background: SlintPalette.alternate-background;
    out property <color> text-primary: SlintPalette.alternate-foreground;
    out property <color> text-secondary: SlintPalette.accent-foreground;
}
